import pytest
from mkdocs.exceptions import Abort

WARNING_MESSAGE = "awesome-nav: 'nav' config from mkdocs.yml is being replaced with one generated by awesome-nav (monorepo plugin detected and nav contains non include statements)"
EXCEPTION_MESSAGE = "Aborted with 1 warnings in strict mode!"


@pytest.fixture(autouse=True)
def _test_files(mkdocs):
    mkdocs.files(
        """
        mkdocs.yml
        | strict: true
        | site_name: Test
        | plugins:
        |   - awesome-nav
        |   - monorepo
        | nav:
        |   - sub: '!include ./sub/mkdocs.yml'
        """
    )


def test_default_nav(mkdocs, logs):
    mkdocs.files(
        """
        docs/
            foo.md
        sub/
            docs/
                bar.md
            mkdocs.yml
            | site_name: sub
        """
    )

    mkdocs.build().assert_nav(
        """
        - Foo: foo.md
        - Sub:
            - Bar: sub/bar.md
        """
    )

    assert logs.from_plugin == []


def test_nav_in_root(mkdocs, logs):
    mkdocs.files(
        """
        docs/
            foo.md
            .nav.yml
            | nav:
            |   - Title: sub
            |   - foo.md
        sub/
            docs/
                bar.md
            mkdocs.yml
            | site_name: sub
        """
    )

    mkdocs.build().assert_nav(
        """
        - Title:
            - Bar: sub/bar.md
        - Foo: foo.md
        """
    )

    assert logs.from_plugin == []


def test_nav_in_sub(mkdocs, logs):
    mkdocs.files(
        """
        docs/
            foo.md
        sub/
            docs/
                bar.md
                .nav.yml
                | nav:
                |   - Title: bar.md
            mkdocs.yml
            | site_name: sub
        """
    )

    mkdocs.build().assert_nav(
        """
        - Foo: foo.md
        - Sub:
            - Title: sub/bar.md
        """
    )

    assert logs.from_plugin == []


def test_nav_include_in_sub_strict(mkdocs, logs):
    """
    Test that a nav with non include statement will fail in strict build mode

    Given that any structure defined in nav will be ignored we only support top level "include" statements
    """
    mkdocs.files(
        """
        mkdocs.yml
        | strict: true
        | site_name: Test
        | plugins:
        |   - monorepo
        |   - awesome-nav
        | nav:
        |   - foo:
        |      - sub: '!include ./sub/mkdocs.yml'
        docs/
            foo.md
        sub/
            docs/
                bar.md
            mkdocs.yml
            | site_name: sub
        """
    )

    with pytest.raises(Abort) as ex:
        mkdocs.build()

    assert str(ex.value) == EXCEPTION_MESSAGE

    assert logs.from_plugin == [logs.warning(WARNING_MESSAGE)]


def test_nav_vanilla_and_include_strict(mkdocs, logs):
    """
    Test that a nav with non "include" statement will fail in strict build mode
    """
    mkdocs.files(
        """
        mkdocs.yml
        | strict: true
        | site_name: Test
        | plugins:
        |   - monorepo
        |   - awesome-nav
        | nav:
        |   - sub: '!include ./sub/mkdocs.yml'
        |   - foo.md
        docs/
            foo.md
        sub/
            docs/
                bar.md
            mkdocs.yml
            | site_name: sub
        """
    )

    with pytest.raises(Abort) as ex:
        mkdocs.build()

    assert str(ex.value) == EXCEPTION_MESSAGE

    assert logs.from_plugin == [logs.warning(WARNING_MESSAGE)]


def test_nav_vanilla_strict(mkdocs, logs):
    """
    Test that a nav with non "include" statement will fail in strict build mode
    """
    mkdocs.files(
        """
        mkdocs.yml
        | strict: true
        | site_name: Test
        | plugins:
        |   - monorepo
        |   - awesome-nav
        | nav:
        |   - foo.md
        docs/
            foo.md
        """
    )

    with pytest.raises(Abort) as ex:
        mkdocs.build()

    assert str(ex.value) == EXCEPTION_MESSAGE

    assert logs.from_plugin == [logs.warning(WARNING_MESSAGE)]


def test_nav_wildcard(mkdocs, logs):
    mkdocs.files(
        """
        mkdocs.yml
        | strict: true
        | site_name: Test
        | plugins:
        |   - monorepo
        |   - awesome-nav
        | nav:
        |   - sub: '*include ./sub*/mkdocs.yml'
        docs/
            foo.md
        sub/
            docs/
                bar.md
            mkdocs.yml
            | site_name: sub
        sub2/
            docs/
                baz.md
            mkdocs.yml
            | site_name: sub2
        """
    )

    mkdocs.build().assert_nav(
        """
        - Foo: foo.md
        - Sub:
            - Bar: sub/bar.md
        - Sub2:
            - Baz: sub2/baz.md
        """
    )

    assert logs.from_plugin == []


def test_nav_with_vanilla_sub_strict(mkdocs, logs):
    """
    Test that a nav with non "include" statement will fail in strict build mode
    """
    mkdocs.files(
        """
        mkdocs.yml
        | strict: true
        | site_name: Test
        | plugins:
        |   - monorepo
        |   - awesome-nav
        | nav:
        |   - sub: '!include ./sub/mkdocs.yml'
        |   - bar:
        |     - bar.md
        docs/
            foo.md
            bar.md
        sub/
            docs/
                bar.md
            mkdocs.yml
            | site_name: sub
        sub2/
            docs/
                bar.md
            mkdocs.yml
            | site_name: sub2
        """
    )

    with pytest.raises(Abort) as ex:
        mkdocs.build()

    assert str(ex.value) == EXCEPTION_MESSAGE

    assert logs.from_plugin == [logs.warning(WARNING_MESSAGE)]
