site_name: Awesome Nav for MkDocs
strict: true
repo_url: https://github.com/lukasgeiter/mkdocs-awesome-nav

theme:
  name: material
  favicon: favicon.svg
  icon:
    logo: material/compass
    repo: material/github

  features:
    - navigation.tabs
    - navigation.footer
    - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - extra.css

plugins:
  - search
  - awesome-nav

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
