from mkdocs.config import Config, config_options
from mkdocs.config.defaults import MkDocsConfig
from mkdocs.plugins import BasePlugin, event_priority
from mkdocs.structure.files import Files
from mkdocs.structure.nav import Navigation, get_navigation
from mkdocs.structure.pages import Page

from mkdocs_awesome_nav.log import log_warning
from mkdocs_awesome_nav.nav.context import MkdocsFilesContext
from mkdocs_awesome_nav.nav.directory import RootNavDirectory


class AwesomeNavConfig(Config):
    filename = config_options.Type(str, default=".nav.yml")


class AwesomeNavPlugin(BasePlugin[AwesomeNavConfig]):
    def _validate_monorepo_nav(self, nav) -> bool:
        """
        Validates the structure of the navigation configuration when using the monorepo plugin.

        The validation rules are as follows:
        - Each item in the nav configuration must be a dictionary.
        - The value of each dictionary item must be a string.
        - The string value must start with either '!include' or '*include'.

        Parameters:
        nav (list): The navigation configuration to be validated.

        Returns:
        bool: True if the navigation configuration is valid for a monorepo, False otherwise.
        """
        for item in nav:
            if type(item) is not dict:
                return False

            value = list(item.values())[0]
            if type(value) is not str:
                return False

            if not (value.startswith('!include') or value.startswith('*include')):
                return False

        return True

    @event_priority(100)
    def on_config(self, config: MkDocsConfig) -> MkDocsConfig:
        """
        Perform validation during "on_config" phase for cases where plugins modify the structure (Ex. monorepo plugin).
        """
        if config.nav is None:
            return config

        if "monorepo" in config.plugins:
            if not self._validate_monorepo_nav(config.nav):
                log_warning("'nav' config from mkdocs.yml is being replaced with one generated by awesome-nav (monorepo plugin detected and nav contains non include statements)")
        else:
            log_warning("'nav' config from mkdocs.yml is being replaced with one generated by awesome-nav")

        return config

    @event_priority(100)
    def on_nav(self, nav: Navigation, config: MkDocsConfig, files: Files) -> Navigation:
        context = MkdocsFilesContext(files, self.config.filename)

        # clear pages created by mkdocs
        for file in files.documentation_pages():
            # check type for compatibility with material blog (preserve View objects)
            if type(file.page) is Page:
                file.page = None

        original_nav_config = config.nav
        config.nav = RootNavDirectory(context.root).resolve(context).to_mkdocs_config()
        nav = get_navigation(files, config)
        config.nav = original_nav_config

        return nav
