name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # once a week

env:
  UV_VERSION: 0.5.12

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install dependencies
        run: uv sync
      - name: Check formatting
        run: uv run ruff format --check
      - name: Check linting
        run: uv run ruff check --output-format=github
      - name: Check types
        run: uv run mypy .
