name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  UV_VERSION: 0.6.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install dependencies
        run: uv sync
      - name: Build docs
        run: uv run mkdocs build
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    name: Deploy
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

