name: Publish

on:
  push:
    tags:
      - v*.*.*
env:
  UV_VERSION: 0.6.0

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install dependencies
        run: uv sync
      - name: Set version
        run: sed -i "s/0.0.0/${GITHUB_REF_NAME#v}/g" pyproject.toml
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
